# start from base
FROM ubuntu:18.04
MAINTAINER Timothy Baker <tbaker8@luc.edu>
# tag as ubuntu1804:base

# installing system package dependencies for various tools
RUN apt-get update && apt-get install -y \
  apt-transport-https \
  apt-utils \
  autoconf \
  automake \
  autotools-dev \
  bash \
  build-essential \
  ca-certificates \
  cmake \
  curl \
  default-jre \
  dirmngr \
  ed \
  flex \
  fonts-texgyre \
  gcc \
  git \
  less \
  libboost-all-dev \
  libbz2-dev \
  liblzma-dev \
  libcurl4-gnutls-dev \
  libncurses5-dev \
  libncursesw5-dev \
  libssl-dev \
  lsb-release \
  libtool \
  locales \
  make \
  perl \
  pigz \
  software-properties-common \
  vim-tiny \
  unzip \
  wget \
  zip \
  zlib1g-dev \
  && rm -rf /var/lib/apt/lists/*


# Installing python on ubuntu
COPY requirements.txt /tmp
RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y \
  python3 \
  python3-pip \
  python3-dev && \
  ln -s /usr/bin/python3 /usr/local/bin/python3 && \
  python3 -m pip install -r /tmp/requirements.txt


# FastQC
RUN \
  URL=http://www.bioinformatics.babraham.ac.uk/projects/fastqc \
  && VER=0.11.8 \
  && NAME=fastqc_v${VER} \
  && mkdir -p /tmp/ \
  && wget -O /tmp/${NAME}.zip ${URL}/${NAME}.zip \
  && unzip /tmp/${NAME}.zip -d /tmp/ \
  && chmod -R 755 /tmp/ \
  && ln -s /tmp/FastQC/fastqc /usr/local/bin/fastqc \
  && rm -rf /fastqc_tmp/${NAME}.zip \
  && cd /


# install htslib 1.9
RUN \
  URL=https://github.com/samtools/htslib/releases/download \
  && VER=1.9 \
  && NAME=htslib-${VER} \
  && wget -O /tmp/${NAME}.tar.bz2 ${URL}/${VER}/${NAME}.tar.bz2 \
  && bzip2 -d /tmp/${NAME}.tar.bz2 \
  && tar -xvf /tmp/${NAME}.tar -C /usr/local/bin \
  && cd /usr/local/bin/${NAME} \
  && autoheader \
  && autoconf \
  && ./configure \
  && make \
  && make install \
  && cd /


# installing samtools 1.9
RUN \
  URL=https://github.com/samtools/samtools/releases/download \
  && VER=1.9 \
  && NAME=samtools-${VER} \
  && wget -O /tmp/${NAME}.tar.bz2 ${URL}/${VER}/${NAME}.tar.bz2 \
  && bzip2 -d /tmp/${NAME}.tar.bz2 \
  && tar -xvf /tmp/${NAME}.tar -C /usr/local/bin \
  && cd /usr/local/bin/${NAME} \
  && make \
  && make install \
  && cd /


# install STAR aligner
RUN \
  TARBALL=2.7.0f.tar.gz \
  && NAME=STAR-2.7.0f \
  && wget https://github.com/alexdobin/STAR/archive/${TARBALL} \
  && tar -xzf ${TARBALL} \
  && cd /${NAME}/source \
  && make STAR \
  && ln -s /${NAME}/source/STAR /usr/local/bin/STAR
