# start from base
FROM ubuntu:r35
MAINTAINER Timothy Baker <tbaker8@luc.edu>

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

WORKDIR /pipeline/scion

CMD ["python3", "scion_pipeline.py", "-s", "/pipeline/SampleInfo.csv", "-e", "/pipeline/ExperimentDesign.csv"]
